# Generated by Django 5.2.8 on 2025-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(default="Developer", max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=1, default=10000, max_digits=10),
        ),
    ]
